modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="woodster"
version="1.1.0"
displayName="Woodster"
credits="Jusey1, Burack"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"

[[dependencies.woodster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




