modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="woodster"
version="1.4.0"
displayName="Woodster"
credits="Jusey1, Burack"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"
description="Books & Ladders"

[[dependencies.woodster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




