modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="woodster"
version="1.2.1"
displayName="Woodster"
credits="Jusey1, Burack"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"
description='''
Books & Ladders
'''

[[dependencies.woodster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




