modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="woodster"
version="1.3.1"
displayName="Woodster"
credits="Jusey1, Burack"
displayURL="https://discord.gg/s7QaYGUzZU"
authors="Jusey1"
description="Books & Ladders"

[[dependencies.woodster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




